# VNC is provisioned
---
version: "3.6"
services:
  os:
    platform: "linux/amd64"
    build:
      context: ${CONTEXT}
      dockerfile: ./Dockerfile
      args:
        - BASE=ubuntu:24.04 # Using devel causes cmake to create error
        - DI_RESOURCES=Resources
        - IMAGE_RESOURCES=/app/Resources
        - USER=user
        - DOCKER_USER=wangsen992
        - IMAGE_NAME=dotfiles
        - WORKSPACE_DIR=.
        - HOST_PORT=8888
        - CONTAINER_PORT=8888
    image: ${DOCKER_USER}/${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
    volumes:
      - ${WORKSPACE_DIR}:/mnt/workspace
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    restart: "no"
    command: bash -c "vncserver :2 -select-de XFCE; sudo tail -F /var/log/syslog"
