# VNC is provisioned
---
version: "3.6"
services:
  os:
    platform: "linux/amd64"
    build:
      context: ${CONTEXT}
      dockerfile: ./Dockerfile
      args:
        - BASE=ubuntu:25.10 # Using devel causes cmake to create error
        - USER=user
    image: wangsen992/dotfiles
    container_name: dotfile_container
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
    ports:
      - 8888:8888
    restart: "no"
    command: /bin/zsh
