[ND_GDrive]
type = drive
scope = drive
token = {"access_token":"ya29.A0AfH6SMB4MaC8DpHDQJAQbOF7CYcZD76iKShzAxiDAh-mgspvC247mqwmWtYMeBv_wt66__x9Kx5736OvPf8LVQddDfA-xuGMxtNtlosAMT25IO7Pa1Mvk0gTDHXZsz8VSoY4cRdk95nI5QSKs33-0ZAUv-ysEY9wRQkyY-QVlKbElQ","token_type":"Bearer","refresh_token":"1/TkdHU5l8gNC1b5ecFyDu8FtzoZdzYb4KBkSH-ArJ2Cw","expiry":"2020-11-13T22:50:56.493608458-05:00"}
root_folder_id = 0AA5syyp9o8fuUk9PVA

[CFOG-ND]
type = drive
scope = drive
token = {"access_token":"ya29.a0AfH6SMDidbhWsghC8Fk0VASF9XOgvkwdDWX4VIVDE5fzOVLDyZTSDj0tfUJ6xLAOXEU-pKlNt3gD0bOlta_5qJjR8GCkog2YIziEylYR-XYhURiQypFrveGHuuq2T1zI7i481nlM3CRhJs0ypfAEL5ZQYaW6rqB2NF1Lsg","token_type":"Bearer","refresh_token":"1//0gx6ddS83VJd6CgYIARAAGBASNwF-L9Iru3b9QtV5leR8xO7oOtmKrWC8uPp5DL4EKrWBK_HhkNhng51YOug7dl7Jc5IVhdWbFJo","expiry":"2020-08-11T04:00:31.972786143-04:00"}
team_drive = 0AK_wZGzr2RgKUk9PVA

[CFOG]
type = drive
scope = drive
token = {"access_token":"ya29.a0AfH6SMBR-w8qohIPMhackFTcbvTgAfiFZa-bVudnM_3EApSzr-7DWy2_LlPIBoqlMFYe8_fyHF-uHGcMIFdIIOEmfEsW8kDwJSNEeIqHxZyb5TGY0Q7hIigKwZ0qRgGmWGQGbbEpCbfqeSZx9GTSWi1DoXeeHJrGYbBEQw","token_type":"Bearer","refresh_token":"1//0gyLa1F8yR0a2CgYIARAAGBASNwF-L9IrpoP_IzH2cWT4TismMRmAZ75dxppsBeWpnXQnwlW7xkyyuXKB3COd17kEXJTNejT8eYI","expiry":"2020-11-01T00:41:10.255112146-04:00"}
team_drive = 0AEVXVtOmnfVNUk9PVA

[crc-sftp]
type = sftp
host = crcfe01.crc.nd.edu
user = swang18
pass = fpTWTjg1VEdcNo1GcgcZgr7FEaaTBoJI3scRsg
use_insecure_cipher = false
md5sum_command = md5sum
sha1sum_command = sha1sum

[cfog-bucket]
type = google cloud storage
project_number = cfog-240720
object_acl = bucketOwnerFullControl
bucket_acl = publicReadWrite
location = us-central1
storage_class = REGIONAL
token = {"access_token":"ya29.Gl1DB2Y3CI-L2tvnbNCR-UrNdVQFbqXBZnGwIKQPV6yBuoqJxzdRUUCJ3HnYz-bS_AGstIFiw8GaMfVHv3KrGWYWD2QtSXVaRTckkdhKHNvM6QHZCVKJs5FnC6aYlvs","token_type":"Bearer","refresh_token":"1/3wC5o7H4kgSj_nICBSZA77qWsK9U518BKA-mLs3hSZQ","expiry":"2019-07-12T23:50:17.73089+08:00"}

[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.Gl2JBx5rfdKMSqVZalfO8S30UVxQzYiBxM_AEcQKjWyNfqeoyl4ZWyOojx2LP2V3UanhBBY7oJdug3HVajZWnFcxcgw4blgg0jBWg5GnNaxGiLcAW7j8ZBNHffzMsso","token_type":"Bearer","refresh_token":"1/vVuc5ELdID-n4cYDM0MyS-wWSrEUO1KmqYDN5cMSDas","expiry":"2019-09-20T18:22:07.615916+08:00"}

[term-sg]
type = sftp
host = 34.87.190.116
user = senwang
pass = Pvfu6MRb--N9xWRVj-UhX1aeriGmzNF4_p2b
md5sum_command = md5sum
sha1sum_command = sha1sum

[nscc]
type = sftp
host = nus.nscc.sg
user = e0305043
pass = SO8jlUeOuPQBQoRO3-piv561y0Gryhc-IXHmjA
md5sum_command = md5sum
sha1sum_command = sha1sum

[atlas]
type = sftp
host = atlas6-c01
user = e0305043
pass = -1weQL5eYokMrdQ7cIVk2xP2r7f1ohHfU8j254o
md5sum_command = md5sum
sha1sum_command = sha1sum

[bridges]
type = sftp
host = bridges.psc.edu
user = wangsen
pass = V2OBs6LdKTQ136ggUyGMNbOkTUdtokKrb6hpSA
md5sum_command = md5sum
sha1sum_command = sha1sum

